/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Machine-readable diagnostic. `message` is the human-oriented rendering
 * (stable: identical to what the throwing API puts in the `Error`);
 * `labels` is the machine interface for editors and tooling.
 */
export interface NagaDiagnostic {
  /** Error class: what stage of the pipeline failed. */
  kind: "parse" | "validation" | "backend" | "usage"
  /** Human-readable rendering of the error. */
  message: string
  /**
   * Source locations involved, empty when the error carries no spans
   * (e.g. backend errors or SPIR-V input).
   */
  labels: Array<NagaLabel>
  /** Extra context lines from the frontend, if any. */
  notes: Array<string>
}

/** One source location attached to a diagnostic. */
export interface NagaLabel {
  /** 1-based line number. */
  line: number
  /** 1-based column (bytes) of the start of the span. */
  column: number
  /** Length (bytes) of the span. */
  length: number
  /** What this location refers to. */
  message: string
}

/**
 * Version of the wrapped `naga` crate (e.g. `"30.0.1"`).
 *
 * This reports the upstream recorded in the package.json `naga` field, which
 * the package version tracks (see `scripts/sync-version.mjs`).
 */
export declare function nagaVersion(): string

/**
 * Translate a shader from one language to another.
 *
 * Returns text for every output format except `spv`, which returns the raw
 * SPIR-V word stream as a `Uint8Array` (little-endian bytes). Throws on
 * parse, validation, or backend errors.
 */
export declare function translate(options: TranslateOptions): string | Uint8Array

/**
 * Translate a shader without throwing.
 *
 * Returns `{ ok: true, output }` on success or `{ ok: false, error }` with a
 * structured [`NagaDiagnostic`] on failure.
 */
export declare function translateDetailed(options: TranslateOptions): TranslateResult

/** Options for [`translate`]. */
export interface TranslateOptions {
  /** Input language of `source`. */
  from: "wgsl" | "glsl" | "spv"
  /** Desired output language. */
  to: "wgsl" | "glsl" | "hlsl" | "msl" | "spv" | "dot"
  /** Shader source: text for `wgsl`/`glsl`, raw SPIR-V bytes for `spv`. */
  source: string | Uint8Array
  /**
   * Entry-point stage. Required when the module has more than one entry
   * point and the backend needs a single one (`glsl`, `spv`); otherwise the
   * sole entry point is used automatically.
   */
  stage?: "vertex" | "fragment" | "compute"
  /** Entry-point name. Same resolution rules as `stage`. */
  entryPoint?: string
  /** GLSL output version, e.g. `"310 es"` (default) or `"450"`. */
  glslVersion?: string
  /** HLSL shader model, e.g. `"5_1"` (default), `"6_0"`. */
  hlslShaderModel?: string
  /** Preprocessor definitions for GLSL *input* (`#define key value` pairs). */
  defines?: Record<string, string>
  /** Validator strictness. Defaults to everything enabled. */
  validation?: ValidationOptions
}

/** Result of [`translate_detailed`]. */
export interface TranslateResult {
  ok: boolean
  /** Present when `ok` is true: text, except `Uint8Array` for `spv` output. */
  output?: string | Uint8Array
  /** Present when `ok` is false. */
  error?: NagaDiagnostic
}

/** Parse and validate a WGSL shader. Throws on error. */
export declare function validateWgsl(source: string, validation?: ValidationOptions | undefined | null): void

/**
 * Parse and validate a WGSL shader without throwing.
 *
 * Returns `{ ok: true }` on success or `{ ok: false, error }` with a
 * structured [`NagaDiagnostic`] on failure.
 */
export declare function validateWgslDetailed(source: string, validation?: ValidationOptions | undefined | null): ValidationResult

/**
 * Validator strictness. Every field is optional and defaults to `"all"`;
 * pass `"all"` explicitly inside an array for the same effect, or `[] for
 * none. Names mirror naga exactly (lowercased).
 */
export interface ValidationOptions {
  /**
   * Which validation passes run (`expressions`, `blocks`,
   * `control_flow_uniformity`, `struct_layouts`, `constants`, `bindings`).
   */
  flags?: ("all" | "expressions" | "blocks" | "control_flow_uniformity" | "struct_layouts" | "constants" | "bindings")[]
  /**
   * Allowed IR capabilities, e.g. `"shader_float16"`, `"subgroup"`,
   * `"mesh_shader"`. Restrict these to validate against what a target
   * platform actually accepts instead of everything naga can express.
   */
  capabilities?: ("all" | "immediates" | "float64" | "primitive_index" | "texture_and_sampler_binding_array" | "buffer_binding_array" | "storage_texture_binding_array" | "storage_buffer_binding_array" | "clip_distances" | "cull_distance" | "storage_texture_16bit_norm_formats" | "multiview" | "early_depth_test" | "multisampled_shading" | "ray_query" | "dual_source_blending" | "cube_array_textures" | "shader_int64" | "subgroup" | "subgroup_barrier" | "subgroup_vertex_stage" | "shader_int64_atomic_min_max" | "shader_int64_atomic_all_ops" | "shader_float32_atomic" | "texture_atomic" | "texture_int64_atomic" | "ray_hit_vertex_position" | "shader_float16" | "texture_external" | "shader_float16_in_float32" | "shader_barycentrics" | "mesh_shader" | "mesh_shader_point_topology" | "texture_and_sampler_binding_array_non_uniform_indexing" | "buffer_binding_array_non_uniform_indexing" | "storage_texture_binding_array_non_uniform_indexing" | "storage_buffer_binding_array_non_uniform_indexing" | "cooperative_matrix" | "per_vertex" | "ray_tracing_pipeline" | "draw_index" | "acceleration_structure_binding_array" | "memory_decoration_coherent" | "memory_decoration_volatile" | "shader_int16")[]
  /** Stages where subgroup operations are permitted. */
  subgroupStages?: ("all" | "vertex" | "fragment" | "compute" | "mesh" | "task" | "ray_generation" | "any_hit" | "closest_hit" | "miss")[]
  /** Permitted subgroup operations. */
  subgroupOperations?: ("all" | "basic" | "vote" | "arithmetic" | "ballot" | "shuffle" | "shuffle_relative" | "quad_fragment_compute")[]
}

/** Result of [`validate_wgsl_detailed`]. */
export interface ValidationResult {
  ok: boolean
  error?: NagaDiagnostic
}
